## <span style="color:blue">Introduction to computation in physical sciences</span>
### J Wang and A Wang, [github.com/com-py/intro](https://github.com/com-py/intro) 
### Ch03, `p6-numpy`, Numpy library

In [1]:
import numpy as np

Constants

In [4]:
np.pi, np.e, np.inf, np.nan

(3.141592653589793, 2.718281828459045, inf, nan)

Array creation

In [2]:
np.zeros(3), np.ones(3)

(array([0., 0., 0.]), array([1., 1., 1.]))

In [3]:
np.arange(3)

array([0, 1, 2])

In [4]:
np.linspace(-1,1,5,retstep=True)

(array([-1. , -0.5,  0. ,  0.5,  1. ]), 0.5)

In [5]:
a = np.array([1., 2., 3.])
a

array([1., 2., 3.])

Array indexing and slicing

In [6]:
a[0], a[1], a[-1], a[-2]

(1.0, 2.0, 3.0, 2.0)

In [7]:
a[1:2]

array([2.])

In [8]:
a[:2], a[2:]

(array([1., 2.]), array([3.]))

Element-wise arithmetic

In [9]:
b = np.array([2,2,2])
a + b, a-b

(array([3., 4., 5.]), array([-1.,  0.,  1.]))

In [10]:
a * b, a/b

(array([2., 4., 6.]), array([0.5, 1. , 1.5]))

Array broadcasting

In [11]:
2 + a, np.array([2,2,2]) + a

(array([3., 4., 5.]), array([3., 4., 5.]))

In [28]:
np.array([2,2]) + a

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [12]:
2*a, np.array([2,2,2])*a

(array([2., 4., 6.]), array([2., 4., 6.]))

Array operations

In [13]:
a = np.arange(3)
b = np.array([2,2,2])
np.sum(a * b)

6

In [14]:
np.dot(a, b)

6

In [15]:
np.cross(a, b)

array([-2,  4, -2])

In [16]:
np.flip([1,2,3])

array([3, 2, 1])

In [17]:
np.insert(a, 1, -1)

array([ 0, -1,  1,  2])

In [18]:
np.insert(a, [1,3], [-1,-2])

array([ 0, -1,  1,  2, -2])

2D arrays

In [29]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
A = np.diag([1., 2., 3.], k=0)
A

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [20]:
B = np.diag([1., -1.], k=1)
B

array([[ 0.,  1.,  0.],
       [ 0.,  0., -1.],
       [ 0.,  0.,  0.]])

In [21]:
C = np.diag([1., -1.], k=-1)
C

array([[ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0., -1.,  0.]])

In [30]:
np.transpose(B)

array([[ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0., -1.,  0.]])

In [22]:
A+B+C

array([[ 1.,  1.,  0.],
       [ 1.,  2., -1.],
       [ 0., -1.,  3.]])

Functions

In [23]:
x = np.linspace(-1,1,5)
np.abs(x)

array([1. , 0.5, 0. , 0.5, 1. ])

In [24]:
def f(x):
    return x*x

f(x)

array([1.  , 0.25, 0.  , 0.25, 1.  ])

In [25]:
def g(x):
    if x>0: return 1
    else:   return 0
    
gvec = np.vectorize(g)
gvec(x)

array([0, 0, 0, 1, 1])

In [26]:
np.random.random(), np.random.random(3)

(0.8887652855521309, array([0.98739968, 0.20369024, 0.84627868]))

In [27]:
np.random.randint(low=0, high=10), np.random.randint(0,10,3)

(7, array([0, 5, 1]))