## <span style="color:blue">Introduction to computation in physical sciences</span>
### J Wang and A Wang, [github.com/com-py/intro](https://github.com/com-py/intro) 
### Ch03, `p7-scipy`, Scipy library

Definite integrals

In [1]:
import numpy as np
from scipy.integrate import quad

In [2]:
f = lambda x: 1/np.sqrt(x)
quad(f, 0, 1)

(2.0000000000000004, 5.10702591327572e-15)

In [3]:
a = 1.0
f = lambda x: 1/(x*x+a*a)**2
quad(f, 0, np.inf)

(0.7853981633974483, 1.9448610022155054e-09)

In [4]:
f = lambda x: np.sin(x)**2/x**2
quad(f, 0, np.inf)

C:\Anaconda3\lib\site-packages\scipy\integrate\quadpack.py:385: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  warnings.warn(msg, IntegrationWarning)


(1.5708678849453774, 0.0015587759422626135)

Expansion coefficients, infinite potential well, $\psi=x(a-x)$

In [2]:
psi = lambda x: x*(a-x)
psi2 = lambda x: psi(x)**2
psin = lambda n, x: np.sqrt(2/a)*np.sin(n*pi*x/a)
f = lambda x: psi(x)*psin(n,x)
pi = np.pi
a = 1
A = quad(psi2, 0, a)[0]   # norm
for n in range(1,5):
    print(n, quad(f, 0, a)[0]/np.sqrt(A))

1 0.9992772459953339
2 5.870202015831392e-17
3 0.03701026837019757
4 -6.221452546292864e-17


Differential equation solver

In [34]:
from scipy.integrate import odeint
def drag(v, t):
    b = 1.0
    return -b*v

In [35]:
t = np.linspace(0,1,5)  # time grid
v = 1.0                 # initial velocity
odeint(drag, v, t)

array([[1.        ],
       [0.7788008 ],
       [0.60653067],
       [0.47236657],
       [0.36787947]])

Coupled ode: $ \frac{dx}{dt} = v, \frac{dv}{dt} = -c_1 v$

In [36]:
def drag2(y, t):
    b = 1.0
    v = y[1]
    return [v, -b*v]
y = [0., 1.]                 # y=[x, v], initial pos and velocity
odeint(drag2, y, t)

array([[0.        , 1.        ],
       [0.22119922, 0.77880078],
       [0.39346933, 0.60653067],
       [0.52763344, 0.47236656],
       [0.63212055, 0.36787945]])

Special functions

In [6]:
from scipy.special import erf, gamma, lambertw, spherical_jn
x = 0.5
erf(x), gamma(x), lambertw(x)

(0.5204998778130465, 1.7724538509055159, (0.35173371124919584+0j))

Equation solver

Blackbody radiation, Wien's law: $x^3/(\exp(x)-1), x=h\nu/kT$

In [7]:
from scipy.optimize import fsolve, bisect
f = lambda x: (x-3)*np.exp(x)+3  # freq, x = beta h nu
fsolve(f, [1., 3.])  # freq, x = beta h nu

array([2.27881059e-12, 2.82143937e+00])

In [8]:
lambertw(-3/np.e**3)+3   # analytic solution

(2.8214393721220787+0j)

In [9]:
bisect(f, 1., 5.)   # [1, 5]=bracket

2.821439372122768

In [10]:
f = lambda x: spherical_jn(n,x)
n = 1
bisect(f, 1., 5.), bisect(f, 5., 10.)

(4.493409457909365, 7.725251836938014)

Linear equations and eigenvalues

In [11]:
from scipy.linalg import solve, eigh
A = np.random.random(9).reshape(3,3)
A = A + np.transpose(A)    # form a symmetric matrix
A

array([[1.71865176, 0.78440106, 1.0647321 ],
       [0.78440106, 0.70674838, 1.21531498],
       [1.0647321 , 1.21531498, 1.15157901]])

In [12]:
c = np.random.random(3)
c

array([0.50965419, 0.95224918, 0.47953584])

In [13]:
x = solve(A, c)
x

array([-0.21045712, -0.65083933,  1.29786239])

In [14]:
np.dot(A, x)

array([0.50965419, 0.95224918, 0.47953584])

In [15]:
vals, vecs = eigh(A)
vals, vecs

(array([-0.31107143,  0.60686089,  3.28118968]),
 array([[-0.05962799,  0.76124704, -0.64571468],
        [-0.7460073 , -0.46379005, -0.47788271],
        [ 0.66326285, -0.45321268, -0.59555072]]))

In [16]:
vecs[:,0]

array([-0.05962799, -0.7460073 ,  0.66326285])

In [17]:
np.sum(vecs[:,0]**2)

0.9999999999999997

In [18]:
np.dot(vecs[:,0], vecs[:,1])

-2.220446049250313e-16